name: harmony
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  flutter_svg: ^2.0.14  

  cupertino_icons: 

  firebase_core:

  flutter_bloc: 

  hydrated_bloc: 

  path_provider: 

  firebase_auth:

  dartz:  

  get_it: 

  cloud_firestore:

  just_audio:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 400 
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 500
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf

    - family: SF Pro
      
         
  
