// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4PEGgOufRfrNKcLxkwu5P2dbz6LM-Waw',
    appId: '1:13795656082:web:2df7dcfbb6fcf0ffd4c14b',
    messagingSenderId: '13795656082',
    projectId: 'fb-harmony',
    authDomain: 'fb-harmony.firebaseapp.com',
    storageBucket: 'fb-harmony.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgec4O8z4miszNV1EXW_-nVZf7uuNg3V4',
    appId: '1:13795656082:android:32d050bf5c985e70d4c14b',
    messagingSenderId: '13795656082',
    projectId: 'fb-harmony',
    storageBucket: 'fb-harmony.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsaA8eNBPpV5NAnWF13W9NY3B8h11XL3w',
    appId: '1:13795656082:ios:316aefb5ce869db3d4c14b',
    messagingSenderId: '13795656082',
    projectId: 'fb-harmony',
    storageBucket: 'fb-harmony.firebasestorage.app',
    iosBundleId: 'com.example.harmony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsaA8eNBPpV5NAnWF13W9NY3B8h11XL3w',
    appId: '1:13795656082:ios:316aefb5ce869db3d4c14b',
    messagingSenderId: '13795656082',
    projectId: 'fb-harmony',
    storageBucket: 'fb-harmony.firebasestorage.app',
    iosBundleId: 'com.example.harmony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4PEGgOufRfrNKcLxkwu5P2dbz6LM-Waw',
    appId: '1:13795656082:web:f5d5314034bf2672d4c14b',
    messagingSenderId: '13795656082',
    projectId: 'fb-harmony',
    authDomain: 'fb-harmony.firebaseapp.com',
    storageBucket: 'fb-harmony.firebasestorage.app',
  );
}
